### ISSUE TITLE
IOOBE if argument --output is passed with no value

### ISSUE THREAD

**Issue by akram** [windup/windup-distribution#47]
If I run rhamt-cli with no --output parameter, I have:

```
wadez-wood:servers Akram$  rhamt-cli --input lab-1/simple-sample-app.ear --packages com.acme  --output
Using RHAMT at /Users/Akram/servers/bin/rhamt-cli-4.0.0-SNAPSHOT
> Red Hat Application Migration Toolkit (RHAMT) CLI, version 4.0.0-SNAPSHOT.
RHAMT execution failed due to: Index: 5, Size: 5
java.lang.IndexOutOfBoundsException: Index: 5, Size: 5
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at org.jboss.windup.bootstrap.commands.windup.RunWindupCommand.runWindup(RunWindupCommand.java:154)
	at org.jboss.windup.bootstrap.commands.windup.RunWindupCommand.execute(RunWindupCommand.java:73)
	at org.jboss.windup.bootstrap.Bootstrap.executePhase(Bootstrap.java:454)
	at org.jboss.windup.bootstrap.Bootstrap.run(Bootstrap.java:319)
	at org.jboss.windup.bootstrap.Bootstrap.main(Bootstrap.java:101)


```

**Comment by jsight** [comment]
https://issues.jboss.org/browse/WINDUP-1702

**Comment by jsight** [comment]
Hi @akram, Thank you for your feedback. We will incorporate a fix for this in the next release!

**Comment by jsight** [comment]
Fixed: https://github.com/windup/windup/commit/e06e7b8865d4da692f06a53d75a2ccc63738eccf
